```{r}
library(readr)
library(ggplot2)

getwd()
dir.exists()
res_files <- list.files("tests/results/coxph_res",
                        full.names=TRUE)
print(res_files)
#readr::read_delim("tests/results/study_20_10_2_8_coxph_res.tsv")
```

```{r}
all_coxph_res <- tibble(Endpoint=character(), Score=character(), Group=character(), N_controls=numeric(), N_cases=numeric(), beta=numeric(), std_errs=numeric(), pval=numeric(), HR=numeric(), CI_pos=numeric(), CI_neg=numeric(), Age=numeric())
for(res_file in res_files) {
    curnt_age <- sub("(.+/)(study_)([0-9]+)(_.+)+$", "\\3", res_file)
    coxph_res <- readr::read_delim(res_file, delim="\t", show_col_types=FALSE)
    coxph_res <- tibble::add_column(coxph_res, Age=curnt_age)
    all_coxph_res <- dplyr::bind_rows(all_coxph_res, coxph_res)
}
```
```{r}
dplyr::group_vars(group_coxph_res)
```

```{r}
endpts <- unique(all_coxph_res$Endpoint)
for(endpt in endpts) {
    print(all_coxph_res)
    endpt_coxph_res <- dplyr::filter(all_coxph_res,
                                     Group == "high" &
                                     Endpoint == endpt)

    plt <- ggplot2::ggplot(endpt_coxph_res, aes(x=Age, y=HR)) +
                labs(title=paste0(endpt),
                    subtitle=paste0("Exp: 10 Wash: 2 Obs: 8 Years"),
                    x="Age",
                    y="HR") +
                geom_point() +
                geom_errorbar(aes(ymin=CI_neg, ymax=CI_pos), width=.1) +
                theme_minimal() + 
                theme(text=element_text(size=21))
    print(plt)
}
```