# Setup
```{r}
source("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/scripts/utils.R")

color_list <- get_final_color_list()
bb_colors <- get_bb_colors()
date <- "2024-07-02"
plt_res_dir <- paste0("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/results/plots/", date, "/manuscript/")
tbl_res_dir <- paste0("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/results/tables/", date, "/")
if(!dir.exists(tbl_res_dir)) dir.create(tbl_res_dir, recursive=TRUE)

base_size <- 28
size_small <- 20
size_medium <- 22
font <- "Sans Serif"
axis_line_size <- 1


library(showtext)
library(extrafont)
# Import Open Sans font
font_import(paths = "/home/detrokir/Documents/DSGE/extra/Open_Sans", prompt = FALSE)
loadfonts(device = "win")
# Add Open Sans to showtext
font_add("Open Sans", "/home/detrokir/Documents/DSGE/extra/Open_Sans/OpenSans-Regular.ttf")
showtext_auto()
# Ensure showtext is enabled for ggsave
showtext_opts(dpi = 600) # Set DPI for showtext rendering

# Data
endpt_map <- readr::read_delim("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/results/tables/endpt_name_maps/endpoint_map.csv")
crnt_cidx_path <- "/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/processed/2024-07-02/bbs/meta/2019-01-01_o8_w2_10_32_70_cidx.tsv"
all_cidx <- readr::read_delim(crnt_cidx_path)
crnt_hrs_path <- "/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/processed/2024-07-02/bbs/meta/2019-01-01_o8_w2_10_32_70_coxph.tsv"
all_hrs <- readr::read_delim(crnt_hrs_path)
```


```{r}
base <- "Surv~Sex+Age"
phers <- "Surv~PheRS"
phers_base <- "Surv~PheRS+Sex+Age"
phers_transfer_base <- "Surv~PheRS_transfer+Sex+Age"
phers_transfer <- "Surv~PheRS_transfer"
base_cci <- "Surv~CCI_group+Sex+Age"
cci_edu <- "Surv~CCI_group+Edu+Sex+Age" 
pheno <- "Surv~CCI_group+Edu+PheRS+Sex+Age" 
```


### Panel A

# Base vs. CCI

```{r}
line_size <- 1
point_size <- 4

all_cidx <- readr::read_delim("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/processed/2024-07-02/bbs/meta/2019-01-01_o8_w2_10_32_70_cidx.tsv")
lower_mdl <- base
upper_mdl <- base_cci

crnt_cidx <- dplyr::filter(all_cidx, SURV_MODEL %in% c(lower_mdl, upper_mdl))

crnt_cidx <- crnt_cidx %>% 
                get_new_crnt_endpt_data()   %>%
                mutate(SURV_MODEL=case_when(SURV_MODEL == lower_mdl ~ "mdl1", 
                                            SURV_MODEL == upper_mdl ~ "mdl2")) %>%
                pivot_wider(values_from=c(C_IDX, C_IDX_CI_NEG, C_IDX_CI_POS, SE), names_from=SURV_MODEL, id_cols=c(Endpoint, Biobank))
crnt_cidx$P_VAL_DIFFERENCE <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$pvals)
crnt_cidx
#readr::write_delim(hrs_wide, paste0(res_dir, "sub/comp_models/hrs/cross/prs_vs_phers.tsv"), delim="\t")
crnt_cidx$sign <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$sign)

crnt_cidx$Biobank <- factor(crnt_cidx$Biobank, levels=c("FinnGen", "UKB", "EstB", "Meta-analysis"))
crnt_cidx <- dplyr::filter(crnt_cidx, Biobank != "Meta-analysis")

plt_a <- ggplot( crnt_cidx, aes(x=C_IDX_mdl1, y=C_IDX_mdl2, color=Endpoint, alpha=sign)) +
            scale_alpha_continuous(range=c(0.5, 1)) + guides(alpha=FALSE) +
            # Guide Lines
            geom_hline(yintercept=0.5, linetype=1, size=line_size) +
            geom_vline(xintercept=0.5, linetype=1, size=line_size) +
            geom_abline(intercept=0, slope=1, linetype=6, size=line_size) +
            # Confidence intervals
            # Data
            geom_linerange(aes(xmin=C_IDX_CI_NEG_mdl1, xmax=C_IDX_CI_POS_mdl1), size=line_size) +
            geom_linerange(aes(ymin=C_IDX_CI_NEG_mdl2, ymax=C_IDX_CI_POS_mdl2), size=line_size) +
            geom_point(size=point_size) +
            # Scales
            scale_color_manual(values=color_list, name="") +
            # Limits
            # Theme
            theme_comp(base_size=base_size) +
            labs(x="", y="", title="", subtitle="")  +
            facet_wrap(~Biobank, nrow=1) +
            theme_comp(base_size=base_size, legend_pos="none", plot_top_margin=-30, legend_box_spacing=0) +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))
plt_a 

#ggsave(paste0(res_dir, "sub/comp_models/cidx/cross/increase/base_vs_full.png"), fig_a, width=17, height=7, bg="white", dpi=300)
```


# Panel - B

## attenuation CCI HRs

```{r}
point_size <- 4
line_size <- 1
lower_mdl <- cci_edu
upper_mdl <- pheno

crnt_hrs <- dplyr::filter(all_hrs, SURV_MODEL %in% c(lower_mdl, upper_mdl))

crnt_hrs <- crnt_hrs %>% 
                get_new_crnt_endpt_data()   %>%
                mutate(SURV_MODEL=case_when(SURV_MODEL == lower_mdl ~ "mdl1", 
                                            SURV_MODEL == upper_mdl ~ "mdl2")) %>% 
                filter(VAR == "CCI") %>%
                pivot_wider(values_from=c(HR, CI_NEG, CI_POS, BETA, BETA_SE), names_from=SURV_MODEL, id_cols=c(Endpoint, Biobank))
crnt_hrs$sign <- as.numeric(calc_hr_pval(crnt_hrs %>% select(BETA_mdl1, BETA_SE_mdl1), crnt_hrs %>% select(BETA_mdl2, BETA_SE_mdl2))$sign)

crnt_hrs$Biobank <- factor(crnt_hrs$Biobank, levels=c("FinnGen", "UKB", "EstB", "Meta-analysis"))
crnt_hrs <- dplyr::filter(crnt_hrs, Biobank != "Meta-analysis")
crnt_hrs <- crnt_hrs %>% left_join(endpt_map)
plt_b <- ggplot( crnt_hrs, aes(x=HR_mdl1, y=HR_mdl2, color=Endpoint)) +
           scale_alpha_continuous(range=c(0.5, 1)) + guides(alpha=FALSE) +
            # Guide Lines
            geom_hline(yintercept=1, linetype=1, size=line_size) +
            geom_vline(xintercept=1, linetype=1, size=line_size) +
            geom_abline(intercept=0, slope=1, linetype=6, size=line_size) +
            # Confidence intervals
            # Data
            geom_linerange(aes(xmin=CI_NEG_mdl1, xmax=CI_POS_mdl1), size=line_size) +
            geom_linerange(aes(ymin=CI_NEG_mdl2, ymax=CI_POS_mdl2), size=line_size) +
            geom_point(size=point_size) +
            # Scales
            scale_color_manual(values=color_list, name="") +
            # Limits
            # Theme
            theme_comp(base_size=base_size) +
            labs(x="", y="", title="", subtitle="")  +
            facet_wrap(~Biobank, nrow=1) +
            coord_cartesian(xlim=c(0.9, 3), ylim=c(0.9, 3)) +
            theme_comp(base_size=base_size, legend_pos="none", plot_top_margin=-30, legend_box_spacing=0) +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))
plt_b + theme(legend.position="none")

#ggsave(paste0(res_dir, "sub/comp_models/cidx/cross/increase/base_vs_full.png"), fig_a, width=17, height=7, bg="white", dpi=300)
```

# Panel - C
per 1-SD
```{r}
line_size=1.9
point_size=7
var <- "CCI"
model <- "Surv~CCI+Sex+Age"
bbs <- names(bb_colors)[names(bb_colors) != "Meta-analysis"]

hrs_data <- all_hrs %>% dplyr::filter(SURV_MODEL == model, VAR==var) %>% get_new_crnt_endpt_data()
hrs_data <- hrs_data %>% dplyr::mutate(highlight=ifelse(Biobank == "Meta-analysis", 1, 0.5)) 

hrs_data <- dplyr::left_join(hrs_data, endpt_map, by=c("Endpoint"="Endpoint")) %>% filter(!is.na(Disease_short)) %>% mutate(Endpoint=Disease_short)
hrs_data <- strip_column(hrs_data, includes_prs=ifelse(var=="PRS", TRUE, FALSE), hrs=TRUE)
hrs_data$Biobank <- factor(hrs_data$Biobank, levels=c(bbs, "Meta-analysis"))
hrs_data <- hrs_data[order(hrs_data$Biobank),]
limits <- c(0.9, 1.3)


plt_c <- ggplot(hrs_data, 
                aes(x=HR, y=reorder(Disease_short, CRNT_ENDPT_ORDER), color=Biobank, alpha=highlight)) +
            geom_linerange(aes(xmin=CI_NEG, xmax=CI_POS), position=position_dodge(0.5), size=line_size, key_glyph=draw_key_rect) +
            # Scale manual
            scale_alpha_continuous(range = c(0.8, 1.3), guide="none") +
            scale_color_manual(values=bb_colors, name="") +
            scale_fill_manual(values = c("white", "grey75"), name="", guide="none") +
            scale_x_continuous(breaks=c(1, 1.25,2, 2.5, 3, 3.5)) +
            coord_cartesian(xlim=limits) + # Does not remove elements that are outside of limits
            # Stripes
            geom_rect(aes(ymax = CRNT_ENDPT_ORDER+0.5, ymin = CRNT_ENDPT_ORDER-0.5, xmin = -Inf, xmax = Inf, fill=stripe), color=NA, alpha = 0.1) +
            # Data points
            geom_point(aes(size=N_CASES), shape=18, position=position_dodge(0.5), key_glyph=draw_key_rect) +
            scale_size_continuous(range = c(point_size/2, point_size), guide="none") +
            # Extra Lines
            geom_vline(xintercept=1, linetype=1, size=axis_line_size) +
            # Theme
            labs(y="", x="", title="", fill=NULL, subtitle="") +
            guides(colour=guide_legend(override.aes = list(shape=15, size=7))) +
            theme_hrs(base_size=base_size, plot_top_margin=-20, legend_pos="none") +
            theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text.x=element_text(size=size_small, family=font),
                  axis.text.y=element_text(size=size_medium, family=font),
                  axis.title=element_text(size=size_medium, family=font))

plt_c
```


# D

```{r}
point_size <- 5
fg_cors <- get_data("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/orig/finngen/fg_down_2024-05-29/fg/PheRS_PRS/2019-01-01_o8_w2_e10_32_70_cors.tsv", "FinnGen")

fg_cors_cciedu <- get_data("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/orig/finngen/fg_down_2024-05-29/fg/EDU_CCI/2019-01-01_o8_w2_e10_32_70_cors.tsv", "FinnGen")

ukb_cors_prs <- get_data("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/orig/ukbb/ukbb_down_2024-07-02/prs/2019-01-01_o8_w2_e10_32_70_cors.tsv", "UKB")
estb_cors <- get_data("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/orig/estbb/estbb_down_2024-06-10/2019-01-01_o8_w2_e6_32_70_cors.tsv", "EstB")

ukb_cors <- get_data("/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/orig/ukbb/ukbb_down_2024-07-02/2019-01-01_o8_w2_e10_32_70_cors.tsv", "UKB")
cors <- bind_rows(fg_cors, ukb_cors, ukb_cors_prs, fg_cors_cciedu, estb_cors) %>% filter(SET == "All") %>% distinct(ENDPOINT, VAR_1, VAR_2, Biobank, .keep_all = TRUE)
#readr::write_delim(cors, "/home/detrokir/Documents/DSGE/projects/onset_prediction/code/onset_prediction/analysis/data/processed/correlations.tsv", delim="\t")

var_1 <- "PheRS"
var_2 <- "CCI"


cors_long <- cors %>% filter(VAR_1==var_1, VAR_2==var_2, SET=="All")
cors_long <- dplyr::left_join(cors_long, endpt_map, by=c("Endpoint"="Endpoint")) %>% filter(!is.na(Disease_short))
endpt_order <- cors_long %>% filter(VAR_1==var_1, VAR_2==var_2, Biobank == "FinnGen") %>% arrange(abs(COR)) %>% mutate(ENDPT_ORDER=1:n(), STRIP=ifelse(ENDPT_ORDER %% 2 == 0, "even", "odd")) %>% select(Endpoint, ENDPT_ORDER, STRIP) 
cors_long <- left_join(cors_long, endpt_order, by="Endpoint") %>% arrange(ENDPT_ORDER)


plt_d <- ggplot(cors_long, aes(x=abs(COR), y=reorder(Disease_short, (ENDPT_ORDER)), color=Biobank)) +
            scale_fill_manual(values = c("white", "grey75"), name="", guide="none") +
            # Guide Lines
            geom_vline(xintercept=0, linetype=1, size=1.3) +
            # Data
            geom_linerange(aes(xmin=abs(CIneg), xmax=abs(CIpos)), size=line_size, position= position_dodge(width=0.3)) +
            geom_point(size=point_size, position = position_dodge(width=0.3)) +
            scale_color_manual(values=bb_colors, name="") +
            # Strip
           geom_rect(aes(ymax = ENDPT_ORDER+0.5, ymin = ENDPT_ORDER-0.5, xmin=-Inf, xmax=Inf, fill=STRIP), color=NA, alpha=0.1) +
           # scale_color_manual(values=bb_colors, name="") +
            # Theme
            theme_hrs(base_size=base_size, legend_pos="none") +
            scale_x_continuous(breaks=c(0, 0.1, 0.2, 0.3, 0.4)) +
            labs(x="", y="", title="", subtitle="")  +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))

plt_d

min(abs(cors_long$COR))
max(abs(cors_long$COR))
mean(abs(cors_long$COR))

```

```{r}
top_plt <- cowplot::plot_grid(plt_a, plt_b, nrow=2, rel_heights=1)
bottom_plt <- cowplot::plot_grid(NULL, plt_c, NULL,plt_d, NULL,nrow=1, rel_widths=c(0.02,0.6, -0.02,0.4,0.02), align="h")
full_plt <- cowplot::plot_grid(NULL, top_plt, NULL, bottom_plt, NULL, nrow=5, rel_heights=c(0.05, 0.65, 0.15, 0.325, 0.025))
full_plt

full_plt

#ggsave(paste0(plt_res_dir, "sup/fig2_v2.pdf"), full_plt, width=22, height=24, dpi=600, unit="in", bg="white")
```