# Setup
```{r}
source("/home/detrokir/Documents/DSGE/GitHub/onset_prediction/analysis/scripts/utils.R")

color_list <- get_final_color_list()
bb_colors <- get_bb_colors()
date <- "2024-08-12"
plt_res_dir <- paste0("/home/detrokir/Documents/DSGE/GitHub/onset_prediction/analysis/results/plots/", date)
tbl_res_dir <- paste0("/home/detrokir/Documents/DSGE/GitHub/onset_prediction/analysis/results/tables/", date, "/")
if(!dir.exists(tbl_res_dir)) dir.create(tbl_res_dir, recursive=TRUE)

base_size <- 28
size_small <- 20
size_medium <- 22
font <- "Sans Serif"
axis_line_size <- 1


library(showtext)
library(extrafont)
# Import Open Sans font
font_import(paths = "/home/detrokir/Documents/DSGE/extra/Open_Sans", prompt = FALSE)
loadfonts(device = "win")
# Add Open Sans to showtext
font_add("Open Sans", "/home/detrokir/Documents/DSGE/extra/Open_Sans/OpenSans-Regular.ttf")
showtext_auto()
# Ensure showtext is enabled for ggsave
showtext_opts(dpi = 600) # Set DPI for showtext rendering

# Data
endpt_map <- readr::read_delim("/home/detrokir/Documents/DSGE/GitHub/onset_prediction/analysis/results/tables/endpt_name_maps/endpoint_map.csv")
crnt_cidx_path <- "/home/detrokir/Documents/DSGE/GitHub/onset_prediction/analysis/data/processed/2024-07-02/bbs/meta/2019-01-01_o8_w2_10_32_70_cidx.tsv"
all_cidx <- readr::read_delim(crnt_cidx_path)
crnt_hrs_path <- "/home/detrokir/Documents/DSGE/GitHub/onset_prediction/analysis/data/processed/2024-07-02/bbs/meta/2019-01-01_o8_w2_10_32_70_coxph.tsv"
all_hrs <- readr::read_delim(crnt_hrs_path)
```

```{r}
base <- "Surv~Sex+Age"
phers <- "Surv~PheRS"
phers_base <- "Surv~PheRS+Sex+Age"
phers_transfer_base <- "Surv~PheRS_transfer+Sex+Age"
phers_transfer <- "Surv~PheRS_transfer"
base_cci <- "Surv~CCI_group+Sex+Age"
cci_edu <- "Surv~CCI_group+Edu+Sex+Age" 
pheno <- "Surv~CCI_group+Edu+PheRS+Sex+Age" 
phers_prs <- "Surv~PheRS+PRS"
phers_prs_base <- "Surv~PheRS+PRS+Sex+Age"
prs_base <- "Surv~PRS+Sex+Age"
line_size <- 1
point_size <- 4
```


### Panel A

# PRS over PheRS 

```{r}
lower_mdl <- phers
upper_mdl <- phers_prs

crnt_cidx <- dplyr::filter(all_cidx, SURV_MODEL %in% c(lower_mdl, upper_mdl))

crnt_cidx <- crnt_cidx %>% 
                get_new_crnt_endpt_data()   %>%
                mutate(SURV_MODEL=case_when(SURV_MODEL == lower_mdl ~ "mdl1", 
                                            SURV_MODEL == upper_mdl ~ "mdl2")) %>%
                pivot_wider(values_from=c(C_IDX, C_IDX_CI_NEG, C_IDX_CI_POS, SE), names_from=SURV_MODEL, id_cols=c(Endpoint, Biobank))
crnt_cidx$P_VAL_DIFFERENCE <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$pvals)
crnt_cidx
#readr::write_delim(hrs_wide, paste0(res_dir, "sub/comp_models/hrs/cross/prs_vs_phers.tsv"), delim="\t")
crnt_cidx$sign <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$sign)

crnt_cidx$Biobank <- factor(crnt_cidx$Biobank, levels=c("FinnGen", "UKB", "EstB", "Meta-analysis"))

plt_a <- ggplot( crnt_cidx, aes(x=C_IDX_mdl1, y=C_IDX_mdl2, color=Endpoint, alpha=sign)) +
            scale_alpha_continuous(range=c(0.5, 1)) + guides(alpha=FALSE) +
            # Guide Lines
            geom_hline(yintercept=0.5, linetype=1, size=line_size) +
            geom_vline(xintercept=0.5, linetype=1, size=line_size) +
            geom_abline(intercept=0, slope=1, linetype=6, size=line_size) +
            # Confidence intervals
            # Data
            geom_linerange(aes(xmin=C_IDX_CI_NEG_mdl1, xmax=C_IDX_CI_POS_mdl1), size=line_size) +
            geom_linerange(aes(ymin=C_IDX_CI_NEG_mdl2, ymax=C_IDX_CI_POS_mdl2), size=line_size) +
            geom_point(size=point_size) +
            # Scales
            scale_color_manual(values=color_list, name="") +
            # Limits
            scale_x_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            scale_y_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            # Theme
            theme_comp(base_size=base_size) +
            labs(x="", y="", title="", subtitle="")  +
            facet_wrap(~Biobank, nrow=1) +
            theme_comp(base_size=base_size, legend_pos="none", plot_top_margin=-30, legend_box_spacing=0) +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))
plt_a 
```
# PRS over PheRS with age and sex

```{r}
lower_mdl <- phers_base
upper_mdl <- phers_prs_base

crnt_cidx <- dplyr::filter(all_cidx, SURV_MODEL %in% c(lower_mdl, upper_mdl))

crnt_cidx <- crnt_cidx %>% 
                get_new_crnt_endpt_data()   %>%
                mutate(SURV_MODEL=case_when(SURV_MODEL == lower_mdl ~ "mdl1", 
                                            SURV_MODEL == upper_mdl ~ "mdl2")) %>%
                pivot_wider(values_from=c(C_IDX, C_IDX_CI_NEG, C_IDX_CI_POS, SE), names_from=SURV_MODEL, id_cols=c(Endpoint, Biobank))
crnt_cidx$P_VAL_DIFFERENCE <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$pvals)
crnt_cidx
#readr::write_delim(hrs_wide, paste0(res_dir, "sub/comp_models/hrs/cross/prs_vs_phers.tsv"), delim="\t")
crnt_cidx$sign <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$sign)

crnt_cidx$Biobank <- factor(crnt_cidx$Biobank, levels=c("FinnGen", "UKB", "EstB", "Meta-analysis"))

plt_b <- ggplot( crnt_cidx, aes(x=C_IDX_mdl1, y=C_IDX_mdl2, color=Endpoint, alpha=sign)) +
            scale_alpha_continuous(range=c(0.5, 1)) + guides(alpha=FALSE) +
            # Guide Lines
            geom_hline(yintercept=0.5, linetype=1, size=line_size) +
            geom_vline(xintercept=0.5, linetype=1, size=line_size) +
            geom_abline(intercept=0, slope=1, linetype=6, size=line_size) +
            # Confidence intervals
            # Data
            geom_linerange(aes(xmin=C_IDX_CI_NEG_mdl1, xmax=C_IDX_CI_POS_mdl1), size=line_size) +
            geom_linerange(aes(ymin=C_IDX_CI_NEG_mdl2, ymax=C_IDX_CI_POS_mdl2), size=line_size) +
            geom_point(size=point_size) +
            # Scales
            scale_color_manual(values=color_list, name="") +
            # Limits
            scale_x_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            scale_y_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            # Theme
            theme_comp(base_size=base_size) +
            labs(x="", y="", title="", subtitle="")  +
            facet_wrap(~Biobank, nrow=1) +
            theme_comp(base_size=base_size, legend_pos="none", plot_top_margin=-30, legend_box_spacing=0) +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))
plt_b 
```


# PheRS over PRS 
```{r}
lower_mdl <- prs
upper_mdl <- phers_prs

crnt_cidx <- dplyr::filter(all_cidx, SURV_MODEL %in% c(lower_mdl, upper_mdl))

crnt_cidx <- crnt_cidx %>% 
                get_new_crnt_endpt_data()   %>%
                mutate(SURV_MODEL=case_when(SURV_MODEL == lower_mdl ~ "mdl1", 
                                            SURV_MODEL == upper_mdl ~ "mdl2")) %>%
                pivot_wider(values_from=c(C_IDX, C_IDX_CI_NEG, C_IDX_CI_POS, SE), names_from=SURV_MODEL, id_cols=c(Endpoint, Biobank))
crnt_cidx$P_VAL_DIFFERENCE <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$pvals)
crnt_cidx
#readr::write_delim(hrs_wide, paste0(res_dir, "sub/comp_models/hrs/cross/prs_vs_phers.tsv"), delim="\t")
crnt_cidx$sign <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$sign)

crnt_cidx$Biobank <- factor(crnt_cidx$Biobank, levels=c("FinnGen", "UKB", "EstB", "Meta-analysis"))

plt_c <- ggplot( crnt_cidx, aes(x=C_IDX_mdl1, y=C_IDX_mdl2, color=Endpoint, alpha=sign)) +
            scale_alpha_continuous(range=c(0.5, 1)) + guides(alpha=FALSE) +
            # Guide Lines
            geom_hline(yintercept=0.5, linetype=1, size=line_size) +
            geom_vline(xintercept=0.5, linetype=1, size=line_size) +
            geom_abline(intercept=0, slope=1, linetype=6, size=line_size) +
            # Confidence intervals
            # Data
            geom_linerange(aes(xmin=C_IDX_CI_NEG_mdl1, xmax=C_IDX_CI_POS_mdl1), size=line_size) +
            geom_linerange(aes(ymin=C_IDX_CI_NEG_mdl2, ymax=C_IDX_CI_POS_mdl2), size=line_size) +
            geom_point(size=point_size) +
            # Scales
            scale_color_manual(values=color_list, name="") +
            # Limits
            scale_x_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            scale_y_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            # Theme
            theme_comp(base_size=base_size) +
            labs(x="", y="", title="", subtitle="")  +
            facet_wrap(~Biobank, nrow=1) +
            theme_comp(base_size=base_size, legend_pos="none", plot_top_margin=-30, legend_box_spacing=0) +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))
plt_c 
```
# PheRS over PRS with age and sex

```{r}
lower_mdl <- prs_base
upper_mdl <- phers_prs_base

crnt_cidx <- dplyr::filter(all_cidx, SURV_MODEL %in% c(lower_mdl, upper_mdl))

crnt_cidx <- crnt_cidx %>% 
                get_new_crnt_endpt_data()   %>%
                mutate(SURV_MODEL=case_when(SURV_MODEL == lower_mdl ~ "mdl1", 
                                            SURV_MODEL == upper_mdl ~ "mdl2")) %>%
                pivot_wider(values_from=c(C_IDX, C_IDX_CI_NEG, C_IDX_CI_POS, SE), names_from=SURV_MODEL, id_cols=c(Endpoint, Biobank))
crnt_cidx$P_VAL_DIFFERENCE <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$pvals)
crnt_cidx
#readr::write_delim(hrs_wide, paste0(res_dir, "sub/comp_models/hrs/cross/prs_vs_phers.tsv"), delim="\t")
crnt_cidx$sign <- as.numeric(calc_cidx_pval(crnt_cidx %>% select(C_IDX_mdl1, SE_mdl1), crnt_cidx %>% select(C_IDX_mdl2, SE_mdl2))$sign)

crnt_cidx$Biobank <- factor(crnt_cidx$Biobank, levels=c("FinnGen", "UKB", "EstB", "Meta-analysis"))

plt_d <- ggplot( crnt_cidx, aes(x=C_IDX_mdl1, y=C_IDX_mdl2, color=Endpoint, alpha=sign)) +
            scale_alpha_continuous(range=c(0.5, 1)) + guides(alpha=FALSE) +
            # Guide Lines
            geom_hline(yintercept=0.5, linetype=1, size=line_size) +
            geom_vline(xintercept=0.5, linetype=1, size=line_size) +
            geom_abline(intercept=0, slope=1, linetype=6, size=line_size) +
            # Confidence intervals
            # Data
            geom_linerange(aes(xmin=C_IDX_CI_NEG_mdl1, xmax=C_IDX_CI_POS_mdl1), size=line_size) +
            geom_linerange(aes(ymin=C_IDX_CI_NEG_mdl2, ymax=C_IDX_CI_POS_mdl2), size=line_size) +
            geom_point(size=point_size) +
            # Scales
            scale_color_manual(values=color_list, name="") +
            # Limits
            scale_x_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            scale_y_continuous(breaks=c(0.5, 0.6, 0.7, 0.8), limits=c(0.5, 0.85)) +
            # Theme
            theme_comp(base_size=base_size) +
            labs(x="", y="", title="", subtitle="")  +
            facet_wrap(~Biobank, nrow=1) +
            theme_comp(base_size=base_size, legend_pos="none", plot_top_margin=-30, legend_box_spacing=0) +
                theme(legend.text=element_text(size=size_medium, family=font), 
                  axis.text=element_text(size=size_small, family=font),
                  axis.title=element_text(size=size_medium, family=font),
                  plot.subtitle=element_text(size=size_medium, family=font))
plt_d 
```




```{r}
top_plt <- cowplot::plot_grid(plt_a, NULL, plt_b, NULL, plt_c, NULL, plt_d, ncol=1, rel_heights = c(0.25, 0.00, 0.25, 0.05, 0.25, 0.02, 0.25))
full_plt <- cowplot::plot_grid(NULL, top_plt, NULL, ncol=1, rel_heights=c(0.075, 0.8, 0.1))
full_plt

full_plt

ggsave(paste0(plt_res_dir, "/sup_fig7_v2.pdf"), full_plt, width=22, height=28, dpi=600, unit="in", bg="white")
```