# Packages
```{r}
library(forestploter)
library(tidyverse)
library(grid)
source("utils.R")
```

# Age strata Comparison 
## PRS
```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$`PRS HRs for 1-SD Increment` <- paste(rep(" ", 40), collapse = " ")
```

```{r}
file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- dplyr::filter(coxph_hrs, ENDPOINT != "I9_SAH")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
prs_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph_b50.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
b50_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph_a50.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
a50_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("black", "#D5694F", "#EAB034"),
                   legend_name = "Age Group",
                   legend_value = c("All", "<50", ">=50"))
g <- forest(endpt_order[-(2:3)],
            est=list(prs_hrs$HR, b50_hrs$HR, a50_hrs$HR),
            lower=list(prs_hrs$CI_NEG, b50_hrs$CI_NEG, a50_hrs$CI_NEG),
            upper=list(prs_hrs$CI_POS, b50_hrs$CI_POS, a50_hrs$CI_POS),
            ci_column=2,
            ref_line=1,
            sizes=0.7,
            xlim=c(0.8,2.5),
            ticks_at=c(1,1.5,2),
            vert_line=c(1,1.5,2),
            xlab="                                                  HR (95% CI)",
            theme=tm)
g
plt_marked <- forestplotter_edit_stripes(g, c(1,2,7), "#FCF4F2", skip_white = FALSE)
plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/HR/2019-01-01_o8_w2_e10_PRS_age_strata_fp"
save_forestplotter(paste0(common_path, "_striped.png"), g)
save_forestplotter(paste0(common_path, "_marked.png"), plt_marked)
```

## CCI 

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$`CCI HRs for 1-SD Increment` <- paste(rep(" ", 35), collapse = " ")
```

```{r}
file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
cci_hrs <- dplyr::filter(coxph_hrs, VAR == "CCI")

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph_b50.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
b50_hrs <- dplyr::filter(coxph_hrs, VAR == "CCI")

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph_a50.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
a50_hrs <- dplyr::filter(coxph_hrs, VAR == "CCI")
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("black", "#D5694F", "#EAB034"),
                   legend_name = "Age Group",
                   legend_value = c("All", "<50", ">=50"))
g <- forest(endpt_order[-(2:3)],
       est=list(cci_hrs$HR, b50_hrs$HR, a50_hrs$HR),
       lower=list(cci_hrs$CI_NEG, b50_hrs$CI_NEG, a50_hrs$CI_NEG),
       upper=list(cci_hrs$CI_POS, b50_hrs$CI_POS, a50_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.5,1.5),
       ticks_at=c(0.5,1,1.5),
       vert_line=c(0.5,1,1.5),
       xlab="HR (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/HR/2019-01-01_o8_w2_e10_CCI_age_strata_fp"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```

## Education 

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$`Education HRs for 1-SD Increment` <- paste(rep(" ", 40), collapse = " ")
```

```{r}
file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
edu_hrs <- dplyr::filter(coxph_hrs, VAR == "EDU")
edu_hrs <- dplyr::mutate(edu_hrs, HR=1+(1-HR), CI_NEG=1+(1-CI_NEG), CI_POS=1+(1-CI_POS))

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph_b50.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
b50_hrs <- dplyr::filter(coxph_hrs, VAR == "EDU")
b50_hrs <- dplyr::mutate(b50_hrs, HR=1+(1-HR), CI_NEG=1+(1-CI_NEG), CI_POS=1+(1-CI_POS))

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_coxph_a50.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
a50_hrs <- dplyr::filter(coxph_hrs, VAR == "EDU")
a50_hrs <- dplyr::mutate(a50_hrs, HR=1+(1-HR), CI_NEG=1+(1-CI_NEG), CI_POS=1+(1-CI_POS))
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("black", "#D5694F", "#EAB034"),
                   legend_name = "Predictor",
                   legend_value = c("All", "<50", ">50"))
g <- forest(endpt_order[-(2:3)],
       est=list(edu_hrs$HR, b50_hrs$HR, a50_hrs$HR),
       lower=list(edu_hrs$CI_NEG, b50_hrs$CI_NEG, a50_hrs$CI_NEG),
       upper=list(edu_hrs$CI_POS, b50_hrs$CI_POS, a50_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.5,2),
       ticks_at=c(0.5,1,1.5),
       vert_line=c(0.5,1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/2019-01-01_o8_w2_e10_CCI_age_strata_fp"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```
