# PRS + PheRS

```{r}
source("/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/utils.R")
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/results/down_08_02_23/down_coxph_02_07_23/endpt_order.tsv"
library(tidyverse)
library(forestploter)
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
```

```{r}
base <- readr::read_delim("/home/kira/duni/helsinki/DSGE/results/down_08_02_23/down_coxph_02_07_23/cidx/2019-01-01_o8_w2_e10_32_70_CCI_Edu_BATCH_SEX_YOB_PCs_cidx.tsv")
base <- tib_by_endpt_order(base, endpt_order)

phers <- readr::read_delim("/home/kira/duni/helsinki/DSGE/results/down_08_02_23/down_coxph_02_07_23/cidx/2019-01-01_o8_w2_e10_32_70_CCI_Edu_PheRS_BATCH_SEX_YOB_PCs_cidx.tsv")
phers <- tib_by_endpt_order(phers, endpt_order)

prs <- readr::read_delim("/home/kira/duni/helsinki/DSGE/results/down_08_02_23/down_coxph_02_07_23/cidx/2019-01-01_o8_w2_e10_32_70_CCI_Edu_PRS_BATCH_SEX_YOB_PCs_cidx.tsv")
prs <- tib_by_endpt_order(prs, endpt_order)

full <- readr::read_delim("/home/kira/duni/helsinki/DSGE/results/down_08_02_23/down_coxph_02_07_23/cidx/2019-01-01_o8_w2_e10_32_70_CCI_Edu_PheRS_PRS_BATCH_SEX_YOB_PCs_cidx.tsv")
full <- tib_by_endpt_order(full, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#748AAA", "#D5694F", "#EAB034", "#224767"),
                   legend_name = "Model",
                   legend_value = c("Base", "PRS", "PheRS", "Full"))
g <- forest(endpt_order[-(3:4)],
       est=list(base$C_IDX, prs$C_IDX, phers$C_IDX, full$C_IDX),
       lower=list(base$C_IDX_CI_NEG, prs$C_IDX_CI_NEG, phers$C_IDX_CI_NEG, full$C_IDX_CI_NEG),
       upper=list(base$C_IDX_CI_POS, prs$C_IDX_CI_POS, phers$C_IDX_CI_POS, full$C_IDX_CI_POS),
       ci_column=3,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/down_08_02_23/down_coxph_02_07_23/cidx/2019-01-01_o8_w2_e10_32_70_CCI_Edu_PheRS_PRS_BATCH_SEX_YOB_PCs"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```


## CCI

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$` ` <- paste(rep(" ", 35), collapse = " ")

file_path_base <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_SEX_YOB_cidx.tsv"
base_cidxs <- readr::read_delim(file_path_base, delim="\t")
base_cidxs <- tib_by_endpt_order(base_cidxs, endpt_order)

file_path_cci <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_SEX_YOB_cidx.tsv"
cci_cidxs <- readr::read_delim(file_path_cci, delim="\t")
cci_cidxs <- tib_by_endpt_order(cci_cidxs, endpt_order)

file_path_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_SEX_YOB_BATCH_PCs_cidx.tsv"
prs_cidxs <- readr::read_delim(file_path_prs, delim="\t")
prs_cidxs <- tib_by_endpt_order(prs_cidxs, endpt_order)

file_path_cci_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_SEX_YOB_BATCH_PCs_cidx.tsv"
cci_prs_cidxs <- readr::read_delim(file_path_cci_prs, delim="\t")
cci_prs_cidxs <- tib_by_endpt_order(cci_prs_cidxs, endpt_order)

file_path_cci_prs_edu <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_Edu_SEX_YOB_BATCH_PCs_cidx.tsv"
cci_prs_edu_cidxs <- readr::read_delim(file_path_cci_prs_edu, delim="\t")
cci_prs_edu_cidxs <- tib_by_endpt_order(cci_prs_edu_cidxs, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#748AAA", "#EAB034"),
                   legend_name = "Model",
                   legend_value = c("Base", "CCI"))
g <- forest(endpt_order[-(2:3)],
       est=list(base_cidxs$C_IDX, cci_cidxs$C_IDX),
       lower=list(base_cidxs$C_IDX_CI_NEG, cci_cidxs$C_IDX_CI_NEG),
       upper=list(base_cidxs$C_IDX_CI_POS, cci_cidxs$C_IDX_CI_POS),
       ci_column=2,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g

plt_marked <- forestplotter_edit_stripes(g, 
                                         c(6,13, 18), 
                                         "#FDF9F0")
plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_CCI_cidx"
save_forestplotter(paste0(common_path, "_marked.png"), plt_marked)
```

# PRS + CCI

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#748AAA", "#224767", "#D5694F"),
                   legend_name = "Model",
                   legend_value = c("Base", "PRS", "PRS+CCI"))
g <- forest(endpt_order[-(2:3)],
       est=list(base_cidxs$C_IDX, prs_cidxs$C_IDX, cci_prs_cidxs$C_IDX),
       lower=list(base_cidxs$C_IDX_CI_NEG, prs_cidxs$C_IDX_CI_NEG, cci_prs_cidxs$C_IDX_CI_NEG),
       upper=list(base_cidxs$C_IDX_CI_POS, prs_cidxs$C_IDX_CI_POS,cci_prs_cidxs$C_IDX_CI_POS),
       ci_column=2,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g

plt_marked <- forestplotter_edit_stripes(g, 
                                         c(6,13, 18), 
                                         "#FDF9F0")
plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_PRSpCCI_cidx"
save_forestplotter(paste0(common_path, "_marked.png"), plt_marked)
```

# PRS + CCI + Edu

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#748AAA", "#D5694F", "#EAB034"),
                   legend_name = "Model",
                   legend_value = c("Base", "PRS+CCI", "PRS+CCI+Edu"))

g <- forest(endpt_order[-(2:3)],
       est=list(base_cidxs$C_IDX, cci_prs_cidxs$C_IDX, cci_prs_edu_cidxs$C_IDX),
       lower=list(base_cidxs$C_IDX_CI_NEG, cci_prs_cidxs$C_IDX_CI_NEG, cci_prs_edu_cidxs$C_IDX_CI_NEG),
       upper=list(base_cidxs$C_IDX_CI_POS, cci_prs_cidxs$C_IDX_CI_POS, cci_prs_edu_cidxs$C_IDX_CI_POS),
       ci_column=2,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g
plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_PRSpCCIpEDU_cidx"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```

# Washout Comparison

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$` ` <- paste(rep(" ", 35), collapse = " ")

file_path_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_SEX_YOB_BATCH_PCs_cidx.tsv"
prs_w2_cidxs <- readr::read_delim(file_path_prs, delim="\t")
prs_w2_cidxs <- tib_by_endpt_order(prs_w2_cidxs, endpt_order)

file_path_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o10_w0_e10_PRS_SEX_YOB_BATCH_PCs_cidx.tsv"
prs_w0_cidxs <- readr::read_delim(file_path_prs, delim="\t")
prs_w0_cidxs <- tib_by_endpt_order(prs_w0_cidxs, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F"),
                   legend_name = "Wash-out",
                   legend_value = c("2 Years", "None"))
g <- forest(endpt_order[-(2:3)],
       est=list(prs_w2_cidxs$C_IDX, prs_w0_cidxs$C_IDX),
       lower=list(prs_w2_cidxs$C_IDX_CI_NEG, prs_w0_cidxs$C_IDX_CI_NEG),
       upper=list(prs_w2_cidxs$C_IDX_CI_POS, prs_w0_cidxs$C_IDX_CI_POS),
       ci_column=2,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_washout_cidx"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```