# Packages
```{r}
library(forestploter)
library(tidyverse)
library(grid)
source("utils.R")
```



## PRS and PRSiYoB

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$`HRs for 1-SD Increment` <- paste(rep(" ", 40), collapse = " ")
```

```{r}
file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_SEX_YOB_BATCH_PCs_coxph.tsv"
prs_hrs_1 <- readr::read_delim(file_path_coxph, delim="\t")
prs_hrs_1 <- dplyr::filter(prs_hrs_1, VAR == "PRS")
prs_hrs_1 <- tib_by_endpt_order(prs_hrs_1, endpt_order)
prs_hrs_1

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_PRSiYOB_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
prs_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")
prs_hrs <- tib_by_endpt_order(prs_hrs, endpt_order)

prsiyob_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS:YEAR_OF_BIRTH")
prsiyob_hrs <- tib_by_endpt_order(prsiyob_hrs, endpt_order)
prsiyob_hrs
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F", "#748AAA"),
                   legend_name = "Predictor",
                   legend_value = c("PRS", "PRS (Interaction Model)", "PRS*Year of Birth"))
g <- forest(endpt_order[-(2:3)],
       est=list(prs_hrs_1$HR, prs_hrs$HR, prsiyob_hrs$HR),
       lower=list(prs_hrs_1$CI_NEG, prs_hrs$CI_NEG, prsiyob_hrs$CI_NEG),
       upper=list(prs_hrs_1$CI_POS, prs_hrs$CI_POS, prsiyob_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.8,2.2),
       ticks_at=c(1,1.5,2),
       vert_line=c(1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm)
g
plt_marked <- forestplotter_edit_stripes(g, c(1,2,5,7,8,9), "#EBF2F8")

plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/HR/2019-01-01_o8_w2_e10_PRS_PRSiYOB_fp"
save_forestplotter(paste0(common_path, "_striped.png"), g)
save_forestplotter(paste0(common_path, "_marked.png"), plt_marked)
```

# Lifetime Comparison
## Data
```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$`PRS HRs for 1-SD Increment` <- paste(rep(" ", 35), collapse = " ")

file_path_bradley <- "/home/kira/duni/helsinki/DSGE/results/HRperSD_FinnGen.csv"
bradley_hrs <- read_bradley_ests(file_path_bradley)
bradley_hrs <- tib_by_endpt_order(bradley_hrs, endpt_order)

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")
coxph_hrs <- dplyr::filter(coxph_hrs, ENDPOINT != "I9_SAH")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
```


## Plotting
```{r}
# Set-up theme
tm_life <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#D5694F", "#224767"),
                   legend_name = "Model",
                   legend_value = c("8 Year Prediction", "Lifetime"))
g <- forest(endpt_order[-(2:3)],
       est=list(coxph_hrs$HR, bradley_hrs$HR),
       lower=list(coxph_hrs$CI_NEG, bradley_hrs$CI_NEG),
       upper=list(coxph_hrs$CI_POS, bradley_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.8,2.2),
       ticks_at=c(1,1.5,2),
       vert_line=c(1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm_life)
g
plt_marked <- forestplotter_edit_stripes(g, c(1,2,7,13), "#EBF2F8")
plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/HR/2019-01-01_o8_w2_e10_PRS_lifetime_fp"
save_forestplotter(paste0(common_path, "_striped.png"), g)
save_forestplotter(paste0(common_path, "_marked.png"), plt_marked)
```

# PRS Interaction

```{r}
file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_PRSiYOB_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- dplyr::filter(coxph_hrs, VAR %in% c("PRS", "PRS:YEAR_OF_BIRTH"))
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
prs_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")
i_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS:YEAR_OF_BIRTH")
```

## Lifetime Comparison

```{r}
g <- forest(endpt_order[-(2:3)],
       est=list(prs_hrs$HR, bradley_hrs$HR),
       lower=list(prs_hrs$CI_NEG, bradley_hrs$CI_NEG),
       upper=list(prs_hrs$CI_POS, bradley_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.8,2.2),
       ticks_at=c(1,1.5,2),
       vert_line=c(1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm_life)
plt_marked <- forestplotter_edit_stripes(g, c(13), "#EBF2F8")
plt_marked <- forestplotter_edit_stripes(plt_marked, c(1,2,7), "#EDEDED", skip_white = TRUE)
plt_marked
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/HR/2019-01-01_o8_w2_e10_PRS_PRSiYOB_lifetime_fp"

save_forestplotter(paste0(common_path, "_striped.png"), g)
save_forestplotter(paste0(common_path, "_marked.png"), plt_marked)
```
