# IHRC Replotting Code
```{r}
library(IHRC)
file_path <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_10_28_22/2019-01-01_o8_w2_e10_PRS_PRSiYOB_SEX_YOB_BATCH_PCs_coxph.tsv"
ana_details <- list()
ana_details$full_res_dir <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_10_28_22/"
ana_details$res_file_name <- "2019-01-01_o8_w2_e10_PRS_PRSiYOB_SEX_YOB_BATCH_PCs_coxph_sorted_HRs.png"
ana_details$down_fctr <- 4
ana_details$study_type <- "backward"
ana_details$obs_end_date <- as.Date("2019/01/01")
ana_details$endpt <- NA
ana_details$exp_len <- 10
ana_details$wash_len <- 2
ana_details$obs_len <- 8
ana_details$preds <- c("PRS", "PRS*YEAR_OF_BIRTH", "SEX", "YEAR_OF_BIRTH")
ana_details$plot_preds <- c("PRS", "PRS*YEAR_OF_BIRTH")
ana_details$write_res <- TRUE
ana_details
coxph_hrs <- readr::read_delim(file_path, delim="\t")

plt <- IHRC::plot_hrs(from_file=TRUE, coxph_hrs=coxph_hrs, ana_details=ana_details, sort_hrs=TRUE)
plt
```


# Forestplot Code

```{r}
library(ggplot2)
library(forestplot)

file_path <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_PRS_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path, delim="\t")

# Create confidence interval column to display
coxph_hrs$`HR (95% CI)` <- sprintf("%.2f (%.2f - %.2f)",
                                     coxph_hrs$HR, coxph_hrs$CI_NEG, coxph_hrs$CI_POS)

coxph_hrs <- dplyr::arrange(coxph_hrs, desc(HR))
coxph_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")

png("/home/kira/duni/helsinki/DSGE/results/down_coxph_10_28_22/2019-01-01_o8_w2_e10_PRS_forestplot.png", res = 600, width = 10, height = 7.5, units = "in")
forestplot(dplyr::select(coxph_hrs, ENDPOINT, N_CASES, N_CONTROLS, `HR (95% CI)`),
           labeltext=coxph_hrs$ENDPOINT,
           mean=coxph_hrs$HR,
           lower=coxph_hrs$CI_NEG,
           upper=coxph_hrs$CI_POS,
           zero=1,
           graph.pos=4,
           line.margin=0.2,
           boxsize=.25,
               txt_gp = fpTxtGp(xlab=gpar(cex=1)),
           xlab="HR (95% CI) for 1-SD Increment") |>
    fp_add_header(ENDPOINT = "Endpoint",
                  N_CASES = "#Cases",
                  N_CONTROLS = "#Controls",
                  `HR (95% CI)` = "HR (95% CI)") |>
    fp_set_zebra_style("#EFEFEF") 

dev.off()
```
