## PRS and PRSiYoB
```{r}
library(forestploter)
source("/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/utils.R")
getwd()
```
```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$` ` <- paste(rep(" ", 35), collapse = " ")

file_path_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers/2019-01-01_o8_w2_e10_PRS_SEX_YOB_BATCH_PCs_cidx.tsv"
prs_cidxs <- readr::read_delim(file_path_prs, delim="\t")
prs_cidxs <- tib_by_endpt_order(prs_cidxs, endpt_order)

file_path_phers <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers_with_age/2019-01-01_o8_w2_e10_PheRS_SEX_YOB_cidx.tsv"
phers_cidxs <- readr::read_delim(file_path_phers, delim="\t")
phers_cidxs <- tib_by_endpt_order(phers_cidxs, endpt_order)

file_path_phers_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers_with_age/2019-01-01_o8_w2_e10_PRS_PheRS_SEX_YOB_BATCH_PCs_cidx.tsv"
phers_prs_icdxs <- readr::read_delim(file_path_phers_prs, delim="\t")
phers_prs_icdxs <- tib_by_endpt_order(phers_prs_icdxs, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F", "#EAB034"),
                   legend_name = "Model",
                   legend_value = c("PRS", "PheRS", "PRS+PheRS"))
g <- forest(endpt_order[-(2:3)],
       est=list(prs_cidxs$C_IDX, phers_cidxs$C_IDX, phers_prs_icdxs$C_IDX),
       lower=list(prs_cidxs$C_IDX_CI_NEG, phers_cidxs$C_IDX_CI_NEG,  phers_prs_icdxs$C_IDX_CI_NEG),
       upper=list(prs_cidxs$C_IDX_CI_POS, phers_cidxs$C_IDX_CI_POS, phers_prs_icdxs$C_IDX_CI_POS),
       ci_column=2,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_PRS_PheRS_with_age_cidx"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```

## HRs

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$` ` <- paste(rep(" ", 35), collapse = " ")

file_path_hrs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers_with_age/2019-01-01_o8_w2_e10_PRS_PheRS_SEX_YOB_BATCH_PCs_coxph.tsv"
all_hrs <- readr::read_delim(file_path_hrs, delim="\t")
phers_hrs <- dplyr::filter(all_hrs, VAR == "PheRS")
prs_hrs <- dplyr::filter(all_hrs, VAR == "PRS")
phers_hrs <- tib_by_endpt_order(phers_hrs, endpt_order)
prs_hrs <- tib_by_endpt_order(prs_hrs, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F"),
                   legend_name = "Predictor",
                   legend_value = c("PRS", "PheRS"))
g <- forest(endpt_order[-(2:3)],
       est=list(prs_hrs$HR, phers_hrs$HR),
       lower=list(prs_hrs$CI_NEG, phers_hrs$CI_NEG),
       upper=list(prs_hrs$CI_POS, phers_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.8,2.2),
       ticks_at=c(1,1.5,2),
       vert_line=c(1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_PheRS_with_age_comp_hr"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```

# Age comp

## C-index

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$` ` <- paste(rep(" ", 35), collapse = " ")

file_path_phers <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers/2019-01-01_o8_w2_e10_PheRS_SEX_YOB_cidx.tsv"
phers_cidx <- readr::read_delim(file_path_phers, delim="\t")
phers_cidx <- tib_by_endpt_order(phers_cidx, endpt_order)

file_path_phers_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers_with_age/2019-01-01_o8_w2_e10_PheRS_SEX_YOB_cidx.tsv"
age_phers_cidxs <- readr::read_delim(file_path_phers_prs, delim="\t")
age_phers_cidxs <- tib_by_endpt_order(age_phers_cidxs, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F"),
                   legend_name = "PheRS",
                   legend_value = c("No Age", "With Age"))
g <- forest(endpt_order[-(2:3)],
       est=list(phers_cidx$C_IDX, age_phers_cidxs$C_IDX),
       lower=list(phers_cidx$C_IDX_CI_NEG, age_phers_cidxs$C_IDX_CI_NEG),
       upper=list(phers_cidx$C_IDX_CI_POS, age_phers_cidxs$C_IDX_CI_POS),
       ci_column=2,
       ref_line=.5,
       sizes=0.7,
       xlim=c(0.5,1),
       ticks_at=c(0.5,0.6,0.7,0.8,0.9,1),
       vert_line=c(0.5,0.6,0.7,0.8,0.9,1),
       xlab="                                                               c-index (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_PheRS_with_age_comp_cidx"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```


## HR

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")
endpt_order$` ` <- paste(rep(" ", 35), collapse = " ")

file_path_phers <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers/2019-01-01_o8_w2_e10_PheRS_SEX_YOB_coxph.tsv"
phers_hrs <- readr::read_delim(file_path_phers, delim="\t")
phers_hrs <- dplyr::filter(phers_hrs, VAR == "PheRS")
phers_hrs <- tib_by_endpt_order(phers_hrs, endpt_order)

file_path_phers_prs <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_30_22_phers_with_age/2019-01-01_o8_w2_e10_PheRS_SEX_YOB_coxph.tsv"
age_phers_hrs <- readr::read_delim(file_path_phers_prs, delim="\t")
age_phers_hrs <- dplyr::filter(age_phers_hrs, VAR == "PheRS")
age_phers_hrs <- tib_by_endpt_order(age_phers_hrs, endpt_order)
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F"),
                   legend_name = "PheRS",
                   legend_value = c("No Age", "With Age"))
g <- forest(endpt_order[-(2:3)],
       est=list(phers_hrs$HR, age_phers_hrs$HR),
       lower=list(phers_hrs$CI_NEG, age_phers_hrs$CI_NEG),
       upper=list(phers_hrs$CI_POS, age_phers_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.8,2.2),
       ticks_at=c(1,1.5,2),
       vert_line=c(1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm)
g
```

```{r}
common_path <- "/home/kira/duni/helsinki/DSGE/results/forestplots/cidx/2019-01-01_o8_w2_e10_PheRS_with_age_comp_hr"
save_forestplotter(paste0(common_path, "_striped.png"), g)
```


# HRs

```{r}
file_path_endpt_order <- "/home/kira/duni/helsinki/DSGE/Code/onset_prediction/forestplots/endpt_order.tsv"
endpt_order <- readr::read_delim(file_path_endpt_order, delim="\t")

file_path_coxph <- "/home/kira/duni/helsinki/DSGE/results/down_coxph_11_17_22/2019-01-01_o8_w2_e10_CCI_PRS_SEX_YOB_BATCH_PCs_coxph.tsv"
coxph_hrs <- readr::read_delim(file_path_coxph, delim="\t")
coxph_hrs <- tib_by_endpt_order(coxph_hrs, endpt_order)
prs_hrs <- dplyr::filter(coxph_hrs, VAR == "PRS")
cci_hrs <- dplyr::filter(coxph_hrs, VAR == "CCI")

endpt_order$`HRs for 1-SD Increment` <- paste(rep(" ", 35), collapse = " ")
```

```{r}
tm <- forest_theme(base_size = 15,
                   ci_Theight=0.2,
                   refline_lty = "solid",
                   ci_pch = c(19,19),
                   ci_col = c("#224767", "#D5694F"),
                   legend_name = "Predictor",
                   legend_value = c("PRS", "CCI"))
g <- forest(endpt_order[-(2:3)],
       est=list(prs_hrs$HR, cci_hrs$HR),
       lower=list(prs_hrs$CI_NEG, cci_hrs$CI_NEG),
       upper=list(prs_hrs$CI_POS, cci_hrs$CI_POS),
       ci_column=2,
       ref_line=1,
       sizes=0.7,
       xlim=c(0.8,2.2),
       ticks_at=c(1,1.5,2),
       vert_line=c(1,1.5,2),
       xlab="                                                  HR (95% CI)",
       theme=tm)
g
plt_marked_good <- forestplotter_edit_stripes(g, c(6,7,8,13,19), "#FCF4F2")
plt_marked_cancer <- forestplotter_edit_stripes(plt_marked_good, c(1,3,4,10,14,16), "#EDEDED", skip_white = TRUE)

plt_marked_cancer
```
